"use client";
import { useState } from "react";
import { ChevronDown, MapPin, SlidersHorizontal } from "lucide-react";
import { getParcel } from "@/lib/api";
import type { Parcel } from "@/lib/types";

const storyParcels = ["123/4", "124", "125/2", "126", "127/1", "128"];
const layers = ["Parcels", "Survey-number labels", "Village boundary", "Zones", "Tax arrears", "Guideline value", "Roads", "Water lines", "Restriction zones", "Projects", "Change alerts", "Bhuvan WMS overlay"];
export function MapExplorer() {
  const [activeLayers, setActiveLayers] = useState(["Parcels"]); const [colourBy, setColourBy] = useState("land_use"); const [parcel, setParcel] = useState<Parcel | null>(null);
  const toggle = (layer: string) => setActiveLayers((items) => items.includes(layer) ? items.filter((item) => item !== layer) : [...items, layer]);
  return <section className="grid gap-6 lg:grid-cols-[280px_1fr]">
    <aside className="space-y-4 rounded-3xl border border-white/10 bg-white/[0.04] p-5"><div className="flex items-center justify-between"><h1 className="text-xl font-semibold">Map Explorer</h1><SlidersHorizontal size={16} className="text-white/50" /></div>
      {[["Base", layers.slice(0, 3)], ["Essential", layers.slice(3, 4)], ["Use-case", layers.slice(4)]].map(([title, items]) => <details open key={title as string} className="border-t border-white/10 pt-4"><summary className="flex cursor-pointer list-none items-center justify-between text-xs font-semibold uppercase tracking-widest text-white/60">{title}<ChevronDown size={14} /></summary><div className="mt-3 space-y-3">{(items as string[]).map((layer) => <label key={layer} className="flex items-center justify-between text-sm text-white/75"><span>{layer}</span><input type="checkbox" checked={activeLayers.includes(layer)} onChange={() => toggle(layer)} className="accent-emerald-400" /></label>)}</div></details>)}
      <label className="block border-t border-white/10 pt-4 text-xs uppercase tracking-widest text-white/60">Colour parcels by<select value={colourBy} onChange={(event) => setColourBy(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-2 text-sm normal-case tracking-normal text-white"><option className="bg-slate-900">land_use</option><option className="bg-slate-900">ownership_type</option><option className="bg-slate-900">registered</option><option className="bg-slate-900">encumbrance</option><option className="bg-slate-900">dispute</option><option className="bg-slate-900">zone</option><option className="bg-slate-900">permission</option></select></label>
      <label className="flex items-center justify-between border-t border-white/10 pt-4 text-sm text-white/75">3D units preview<input type="checkbox" className="accent-emerald-400" /></label>
    </aside>
    <div className="min-h-[640px] rounded-3xl border border-white/10 bg-[#10251d] p-6 shadow-2xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-emerald-300">Live parcel canvas</p><h2 className="mt-2 text-3xl font-semibold">Chandigarh / Kharar</h2></div><div className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-xs text-white/60">Colour by <strong className="text-white">{colourBy}</strong></div></div><div className="relative mt-6 h-[410px] overflow-hidden rounded-2xl border border-emerald-300/20 bg-[linear-gradient(135deg,rgba(16,185,129,.2)_1px,transparent_1px),linear-gradient(45deg,rgba(16,185,129,.12)_1px,transparent_1px)] bg-[size:42px_42px]"><div className="absolute inset-10 grid grid-cols-4 grid-rows-3 gap-2 opacity-80">{Array.from({ length: 12 }, (_, index) => <button type="button" key={index} onClick={async () => setParcel(await getParcel("ULPIN-1403-PB-889"))} className="group relative border border-emerald-300/30 bg-emerald-400/10 transition hover:bg-emerald-300/30"><MapPin className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-emerald-200 opacity-0 transition group-hover:opacity-100" size={18} /></button>)}</div><div className="absolute bottom-4 left-4 rounded-lg bg-black/40 px-3 py-2 text-xs text-white/70">Click a parcel to open profile</div></div><div className="mt-5 flex flex-wrap gap-2">{storyParcels.map((item) => <button type="button" key={item} onClick={async () => setParcel(await getParcel("ULPIN-1403-PB-889"))} className="rounded-full border border-white/10 px-3 py-2 text-xs text-white/70 hover:border-emerald-300/50 hover:text-white">Story {item}</button>)}</div>{parcel && <ParcelDrawer parcel={parcel} onClose={() => setParcel(null)} />}</div>
  </section>;
}
function ParcelDrawer({ parcel, onClose }: { parcel: Parcel; onClose: () => void }) { const [tab, setTab] = useState("Overview"); const tabs = ["Overview", "Ownership", "Registration", "Planning", "Fiscal", "Utilities", "Satellite"]; return <aside className="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto border-l border-white/10 bg-[#08100C] p-6 shadow-2xl"><button type="button" onClick={onClose} className="float-right text-white/60 hover:text-white">Close</button><p className="text-xs uppercase tracking-widest text-emerald-300">Parcel profile</p><h2 className="mt-2 text-2xl font-semibold">{parcel.identifiers.ulpin}</h2><div className="mt-4 flex flex-wrap gap-2">{parcel.status.map((status) => <span key={status} className="rounded-full border border-emerald-300/30 px-3 py-1 text-xs text-emerald-200">Status: {status}</span>)}</div><div className="mt-6 flex flex-wrap gap-2">{tabs.map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`rounded-full px-3 py-2 text-xs ${tab === item ? "bg-white text-black" : "bg-white/10 text-white/70"}`}>{item}</button>)}</div><div className="mt-6 space-y-4 text-sm text-white/75"><p><strong className="text-white">{tab}</strong> data panel ready for backend wiring.</p><p className="rounded-xl border border-white/10 bg-white/[0.04] p-4">Provenance: State RoR · <span className="text-emerald-300">ok</span></p><button type="button" onClick={() => navigator.clipboard?.writeText(parcel.identifiers.ulpin)} className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-black">Copy ULPIN</button></div></aside>; }
